# Generated by Django 4.1.1 on 2022-09-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='topics',
            field=models.ManyToManyField(related_name='news', to='News.topic'),
        ),
    ]
